version: '3.6'
services:

  servicemock:
    image: damianmcdonald/servicemock:1.0.0
    environment:
     - SERVICEMOCK_LOGS=/app/logs
    volumes:
      - './servicemock/logs:/app/logs'

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.0.1
    container_name: elasticsearch
    secrets:
      - source: elasticsearch.yml
        target: /usr/share/elasticsearch/config/elasticsearch.yml
    ports: ['9200:9200']
    networks: ['stack']
    healthcheck:
      test: curl -s https://localhost:9200 >/dev/null; if [[ $$? == 52 ]]; then echo 0; else echo 1; fi
      interval: 30s
      timeout: 10s
      retries: 5

  kibana:
    image: docker.elastic.co/kibana/kibana:7.0.1
    container_name: kibana
    secrets:
      - source: kibana.yml
        target: /usr/share/kibana/config/kibana.yml
    ports: ['5601:5601']
    networks: ['stack']
    healthcheck:
      test: curl -s https://localhost:5601 >/dev/null; if [[ $$? == 52 ]]; then echo 0; else echo 1; fi
      interval: 30s
      timeout: 10s
      retries: 5

  logstash:
    image: docker.elastic.co/logstash/logstash:7.0.1
    container_name: logstash
    secrets:
      - source: logstash.yml
        target: /usr/share/logstash/config/logstash.yml
    ports: ['5044:5044']
    networks: ['stack']
    volumes:
      - './logstash/conf:/usr/share/logstash/pipeline'
    command: logstash -f /usr/share/logstash/pipeline/custom-logstash.conf
    healthcheck:
      test: bin/logstash -t
      interval: 60s
      timeout: 50s
      retries: 5

  metricbeat:
    image: docker.elastic.co/beats/metricbeat:7.0.1
    container_name: metricbeat
    volumes:
       - /proc:/hostfs/proc:ro
       - /sys/fs/cgroup:/hostfs/sys/fs/cgroup:ro
       - /:/hostfs:ro
    command: >
      sh -c "metricbeat --strict.perms=false -e &&
             sleep 30 &&
             /usr/local/bin/setup-beat.sh"
    secrets:
      - source: metricbeat.yml
        target: /usr/share/metricbeat/metricbeat.yml
    volumes:
      - './metricbeat/conf/setup-beat.sh:/usr/local/bin/setup-beat.sh'
    networks: ['stack']
    healthcheck:
      test: metricbeat test config
      interval: 30s
      timeout: 15s
      retries: 5

  filebeat:
    image: docker.elastic.co/beats/filebeat:7.0.1
    container_name: filebeat
    command: >
      sh -c "filebeat --strict.perms=false -e &&
             sleep 30 &&
             /usr/local/bin/setup-beat.sh"
    secrets:
      - source: filebeat.yml
        target: /usr/share/filebeat/filebeat.yml
    volumes:
      - './filebeat/conf/setup-beat.sh:/usr/local/bin/setup-beat.sh'
      - './servicemock/logs:/var/log'
    networks: ['stack']
    healthcheck:
      test: filebeat test config
      interval: 30s
      timeout: 15s
      retries: 5

networks: {stack: {}}
# use docker volume to persist ES data outside of a container.
#volumes:
  #es_data:

secrets:
  elasticsearch.yml:
    file: ./elasticsearch/conf/elasticsearch.yml
  kibana.yml:
    file: ./kibana/conf/kibana.yml
  logstash.yml:
    file: ./logstash/conf/logstash.yml
  metricbeat.yml:
    file: ./metricbeat/conf/metricbeat.yml
  filebeat.yml:
    file: ./filebeat/conf/filebeat.yml
